import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { ExpenseButton, HomeButton, SpendingButton } from "./MyButton";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ul className="menu menu-horizontal bg-lime-400/50 flex">
        <li>
            <ClerkProvider>
              <header>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  <li><UserButton></UserButton></li>
                  <li><HomeButton></HomeButton></li>
                  <li><ExpenseButton></ExpenseButton></li>
                  <li><SpendingButton></SpendingButton></li>
                </SignedIn>
              </header>
            </ClerkProvider>
        </li>
        </ul>
          <main>{children}</main>
      </body>
    </html>
  );
}
