import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { ExpenseButton, HomeButton, SpendingButton } from "./MyButton";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

//
//
// working on changing theme (primary color) to add border outlines to text inputs

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-theme="lemonade" className={`${GeistSans.variable}`}>
      <body>
        <ul className="menu menu-horizontal bg-lime-400/50 flex">
          <li><HomeButton></HomeButton></li>
          <li><ExpenseButton></ExpenseButton></li>
          <li><SpendingButton></SpendingButton></li>
        </ul>
      {children}
      </body>
    </html>
  );
}
